# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Takuya/Documents/GitHub/nexys_a7_test/spi_test/microblaze_helloworld/microblaze_helloworld.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_2/design_1_clk_wiz_2.xci
# IP: The module: 'design_1_clk_wiz_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Takuya/Documents/GitHub/nexys_a7_test/spi_test/microblaze_helloworld/microblaze_helloworld.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_2/design_1_clk_wiz_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Takuya/Documents/GitHub/nexys_a7_test/spi_test/microblaze_helloworld/microblaze_helloworld.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_2/design_1_clk_wiz_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Takuya/Documents/GitHub/nexys_a7_test/spi_test/microblaze_helloworld/microblaze_helloworld.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_2/design_1_clk_wiz_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Takuya/Documents/GitHub/nexys_a7_test/spi_test/microblaze_helloworld/microblaze_helloworld.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_2/design_1_clk_wiz_2.xci
# IP: The module: 'design_1_clk_wiz_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Takuya/Documents/GitHub/nexys_a7_test/spi_test/microblaze_helloworld/microblaze_helloworld.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_2/design_1_clk_wiz_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Takuya/Documents/GitHub/nexys_a7_test/spi_test/microblaze_helloworld/microblaze_helloworld.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_2/design_1_clk_wiz_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Takuya/Documents/GitHub/nexys_a7_test/spi_test/microblaze_helloworld/microblaze_helloworld.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_2/design_1_clk_wiz_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
